### PR TITLE
Support for simple pattern expressions in condition tags

### PR DESCRIPTION
**Pull request by LorenzCK**
As described in the [AIML spec 1.0.1](http://www.alicebot.org/TR/2005/WD-aiml/#section-condition) (and [partially discussed here](https://www.chatbots.org/ai_zone/viewthread/1858/)), `<condition>` tags can contain simple pattern expressions in their `value` attributes.

These changes add a generic `aiml_pattern_match` function to perform AIML simple pattern matching (which relies on the regex implementation already present) and uses it in the `parse_condition_tag` function. (Also, some redundant code has been cleaned up.)

Example AIML code, with obvious GoT references, like:
```xml
<category>
    <pattern>WHO AM I</pattern>
    <template>
        <condition name="name">
            <li value="* Snow"><get name="name" />, bastard from the North.</li>
            <li value="*">Your name is <get name="name" />.</li>
            <li>No idea.</li>
        </condition>
    </template>
</category>
```
now works as intended if your `name` variable is set to "Jon Snow".

### CODE REVIEW

**Comment by Dave-Morton** [comment]
@LorenzCK - Before I merge this new code I have to ask... Why did you replace all of the calls to `make_lc()` with calls to `_strtolower()`, which is completely identical? I'll have to admit that when you created that function in your last set of commits I had forgotten about the `make_lc()` function, but now that I'm reminded of it's existence, I think that it's a bit redundant to have them both exist. Truthfully, I prefer the name you gave the function, so I think that `make_lc()` should be removed, and all calls to it should be changed to `_strtoliwer()`, but I'm not currently in a position to make such changes. Would you be willing to make those changes? If not, I can probably make time to do it this weekend.

**Comment by LorenzCK** [comment]
@Dave-Morton Absolutely. In fact, I noticed `make_lc()` only *after* adding the other two identical functions, otherwise I would have used the existing one. In these changes I switched to the new function just because, apart from naming, IMHO a casing conversion function makes more sense in the `library/misc_functions.php` file.

Depending on what you and @Program-O prefer, I can strip out the function change from this pull request and submit another one, replacing all case changes in the code base to the `_tolowercase` and `_touppercase` functions. I should be able to submit the new changes by this evening (late morning on your side of the globe, I guess) :)

**Comment by Dave-Morton** [comment]
That would be great! I'm a bit tied up with other tasks, so wouldn't be able to get to it till late this weekend (and that's a holiday here, so I wouldn't be happy about missing outings). Hey, do you mind if I send you an email? I have a question that Liz ( @Program-O ) and I want to ask, but I'd rather keep it private for now. I have your contact info, but wanted to make sure you had no objections before I send out an email.

**Comment by LorenzCK** [comment]
No objections at all! :relaxed:

**Comment by Dave-Morton** [comment]
Email sent. BTW, if you (or anyone else interested in Program O, for that matter) use Skype, I can be contacted via my handle, which is GeekCaveCreations

**Pull request merged**
