### PR TITLE
change the order of the last 20 logs

### PR DESCRIPTION
**Pull request by tbenjis**
Displaying the last 20 logs should be done in descending order to view the most recent users conversation.

### CODE REVIEW

**Comment by Dave-Morton** [comment]
Good call, @tbenjis . Thanks.

**Comment by Dave-Morton** [comment]
Drat. I just noticed that you made the PR to the `MASTER` branch. In the future could you please make any future pull requests to the `DEV` branch instead? That makes it easier for the development cycle. I've already added this to that branch, so we're good this time. 😄

**Comment by tbenjis** [comment]
My bad, realized that after making the pull request. Not happening in the future :)

**Comment by Dave-Morton** [comment]
no worries. As I said, I made the change to `DEV` already (though I haven't pushed the changes yet - Lots to do first).

**Pull request merged**
