### PR TITLE
Added "ignore case" to preg_match

### PR DESCRIPTION
**Pull request by AlekzNet**
The case should be ignored

### CODE REVIEW

**Comment by Dave-Morton** [comment]
I've looked through the changes you're proposing, and I agree (for now) with most of them. however, you've altered one of the searches in a way that won't help. By altering the code on line 460 to prevent the script from performing matches against underscore wildcards, you're likely to break functionality when an underscore wildcard is used. If you could revert that single line of code I'll see about merging the pull request.

**Comment by AlekzNet** [comment]
The underscore matches are done in the previous section:

```xml
        {
          # 3a.) Create a RegEx to search for underscore wildcards
          $regEx = str_replace('_','(.*)', $category_thatpattern);
          if ($regEx !== $category_thatpattern && preg_match("/$regEx/i",$that) === 1)
          {
            $current_score += $thatpattern_underscore_match;
            $track_matches .= 'thatpattern match with underscore, ';
          }
        }
```

Unless I misunderstand something.

**Comment by AlekzNet** [comment]
Just tested that. Works perfectly.

**Comment by AlekzNet** [comment]
Using the following AIML:

```xml
<category>
<pattern>This is that test</pattern>
 <template>That test should work</template>
</category>

<category>
<pattern>* that</pattern>
<that>That test *</that>
 <template>That test works (the star is at the end)</template>
</category>

<category>
<pattern>* that</pattern>
<that>_ test should work</that>
 <template>That test works (the star is at the beginning)</template>
</category>
```
If I say `This is that test` and then `Testing that`, the answer is always `That test works (the star is at the beginning)`.

**Pull request merged**
