### PR TITLE
fix topic search bug

### PR DESCRIPTION
**Pull request by maxkarl**
Fix bug which creates wrong topic query

### CODE REVIEW

**Comment by Dave-Morton** [comment]
Before I approve/merge this PR, I want to review it locally, but I'm laid up sick, so won't be able to do so until I can get to my desk, probably Tuesday.

**Comment by OverlanAI** [comment]
Its fine, Really looked like a c&p mistake anyway from the line above it.
Anyway already added it and found no problems that are obvious.

**Comment by OverlanAI** [comment]
One problem is not about setting and searching for a topic but how to clear it to null and not make it freak out on the null.
cant have everything i guess.

**Comment by patrickschur** [comment]
@maxkarl Please commit your patch to the dev branch. I can't change the base branch without causing conflicts.

**Pull request closed without merging**
