### PR TITLE
fixed issue in default.page.htm causing dataTables error

### PR DESCRIPTION
**Pull request by tbenjis**

### CODE REVIEW

**Comment by Dave-Morton** [comment]
Which page was this affecting?

**Comment by tbenjis** [comment]
editAiml, editUDAiml and srai_lookup

**Comment by Dave-Morton** [comment]
Very odd. It's actually loading _twice_ in my version, yet I see why you want to add the reference where you did. I'm going to make the changes you suggested, but I'm __also__ going to see about removing the other references. After all, if they aren't working there's no reason to have them there at all.

**Comment by tbenjis** [comment]
That makes sense. I noticed it after doing a fresh install

**Comment by Dave-Morton** [comment]
I'm not certain how it happened, but the script references are now loading out of order, and this isn't a good thing. So I'm refactoring the HTML template so that the script references only appear once, then I'll dynamically load the necessary local script references in their proper location. This will involve much more than simply adding a line of code to the template, but will result in cleaner code.

**Comment by tbenjis** [comment]
noticed spellcheck does not work because of the use of `commonWords` instead of `spellcheck_common_words` in spell_checker.php.

Added the change to this commit.

**Comment by Dave-Morton** [comment]
I've pushed the expanded version of this merge request. Please download and test it to see if it works for you.

**Comment by tbenjis** [comment]
Works fine!

**Comment by Dave-Morton** [comment]
Thanks for testing it for me. It worked fine here, too, but it's good to have verification.

I'm shutting my dev computer down this afternoon, but you should be in good hands with @patrickschur  and @Program-O until I get back online.

**Pull request closed without merging**
