### PR TITLE
Fixed errors, added <script>

### PR DESCRIPTION
**Pull request by AlekzNet**

### CODE REVIEW

**Comment by Dave-Morton** [comment]
WOW, you've really made some significant changes to the XSD file, @AlekzNet ! I'm in the middle of homework right now, so don't have time to work out all of the "red" and "green" sections in the new file, but I'
ll be able to get into it tomorrow evening, and probably merge it then. Then I'll ask you about another aspect of the XSD file that also needs attention. Meanwhile, Happy Halloween! :)

**Comment by AlekzNet** [comment]
Actually, I closed this pull request, because it's a duplicate of https://github.com/Program-O/Program-O/pull/176.

**Comment by Dave-Morton** [comment]
but this one is the one with the button to merge it, whereas #176 did not, so... :-P

**Comment by AlekzNet** [comment]
Pff... weird... Ah, probably because it the latest request.

**Comment by AlekzNet** [comment]
The content is based upon https://www.w3.org/TR/xhtml1-schema/#xhtml1-transitional. I checked this XSD file against http://www.utilities-online.info/xsdvalidation/. - looks OK. I'm tweaking it along with reuploading my old AIML files. Managed to catch some errors in both XSD and AIML. So, looks very promising.

I'm closing #176  to avoid confusion.

**Pull request merged**
