### PR TITLE
be sure ZipArchive exists to prevent server error when downloading

### PR DESCRIPTION
**Pull request by tbenjis**
Since ZipArchive is used, lets check if it exists before calling the class to prevent a server error.

### CODE REVIEW

**Comment by Dave-Morton** [comment]
This is a good idea, but let's not forget the upload page as well. this may take a bit more work than just a simple warning (which I would like to reword to indicate that downloading of individual AIML files is still possible - See suggestion below).

For the warning message, I think it should read something like this:

> The PHP ZipArchive class is not available on this server, so Zip files cannot be downloaded. However, individual AIML files can still be downloaded. We apologise for the inconvenience.

Something similarly appropriate for the upload page should also be implemented.

**Comment by tbenjis** [comment]
Sure that make sense. So if a user tries uploads a zip file without ZipArchive class on the server, the error message is displayed. Also, if ZipArchive class is not available during download, the selected files are downloaded individually without conversion to zip.

**Comment by Dave-Morton** [comment]
Exactly. 👍

**Comment by tbenjis** [comment]
I guess the new commit should resolve these issues as discussed. Thanks.

**Comment by tbenjis** [comment]
Oh yea, will make the change now.

**Comment by Dave-Morton** [comment]
Ideal. Thanks. 👍

**Comment by Dave-Morton** [comment]
After syncing this PR on my dev box and inserting some debugging/testing code  I noticed that the links weren't showing up, so I've made some adjustments to have the links show up in the "error" div instead. I'm hosting a garage sale today and tomorrow, so I'm stuck with the laptop, which doesn't have the resources to publish the changes I've made, but I'll try to push them from my desktop this evening.

**Comment by tbenjis** [comment]
Ok, thanks for the update.

**Comment by Dave-Morton** [comment]
I was able to get the changes pushed. You'll notice that I've slightly altered the code and added a way to test it by manually setting$ZipEnabled to false (it's commented out for production, but can be uncommented for testing). I also altered the width of the `errMsg` div wso that it won't cover up the logo.

**Pull request merged**
