### PR TITLE
docker environment with php7.4 and apache

### PR DESCRIPTION
**Pull request by mbrioski**
I have created a docker-compose environment to start working on your project.
I was able to install the project and start working on it with these changes.

It is enough to spin up containers using:

```docker-compose up --build -d```

### CODE REVIEW

**Comment by patrickschur** [comment]
Thank you for your support, but actually we stopped the development of Program-O some time ago. Anyway I will ask the others what they think about it.

**Comment by ridesoft** [comment]
I saw that it is not maintain anymore.
I was interested to understand the logic behind the project and maybe reuse some parts for a personal project.
Do u think it is possible, mentioning u of course? 
Do u have a documentation for this project?

Thanks

**Comment by patrickschur** [comment]
There is no documentation except of a few pages on the wiki. Maybe this site will help you.
https://github.com/Program-O/Program-O/wiki/Using-the-Program-O-API

Tip: Turn on debugging and look at the actual output. This will hopefully help you to understand what Program-O is actually doing.

What do you mean by mentioning? The code is published under GPLv3. You can modifiy if you want but the copyright and license notices must be preserved.

If you only want to understand the logic or use some code snippets feel free to use. If you have any questions let us now. :)

**Comment by tomolimo** [comment]
Hello @patrickschur 
> Thank you for your support, but actually we stopped the development of Program-O some time ago.

Could you give the reasons why it has been stopped?
Thank you
Regards,
Tomolimo

**Comment by AlekzNet** [comment]
> Could you give the reasons why it has been stopped?
Usual reasons: absence of time, other interests, life, the amount of work, lack of adequate amount of developers, etc.

**Comment by patrickschur** [comment]
@tomolimo 
@AlekzNet already described it. Further information can be found on issue #468 where I already talked about this topic.

**Comment by ridesoft** [comment]
Hi, i don't know if this could be of any interest for you but i have just started to develop a PHP library for AIML files. I do it in my free time, so any help is really welcome.

This is the repository: https://github.com/ridesoft/AIML

**Comment by AlekzNet** [comment]
@ridesoft 
> i have just started to develop a PHP library for AIML files.
Will it be AIMLv2 or AIMLv1?

**Comment by ridesoft** [comment]
For now i have started with a basic implementation that work for both.... but i will probably do the version 2

**Comment by AlekzNet** [comment]
v1 is a subset of v2. So, v2 is an obvious choice.

**Pull request closed without merging**
